# Generated by Django 5.1.4 on 2025-03-27 16:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_defuncion', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(help_text='Ingrese una breve biografia del autor', max_length=2000)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del género literario. (Ej: Fantasía, Terror...)', max_length=200)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el idioma (Ej:Inglés, Español, Italiano...)', max_length=200)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('resumen', models.TextField(help_text='Ingrese un breve resumen del libro', max_length=2000)),
                ('isbn', models.CharField(help_text='Ingrese el ISBN del libro', max_length=13, verbose_name='ISBN')),
                ('editorial', models.CharField(help_text='Ingrese la editorial del libro', max_length=200)),
                ('autor', models.ManyToManyField(help_text='Seleccione un autor para este libro', to='catalogo.autor')),
                ('genero', models.ManyToManyField(help_text='Escoja un genero para este libro', to='catalogo.genero')),
                ('idioma', models.ForeignKey(help_text='Seleccione el idioma del libro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.idioma')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='EjemplarLibro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para este ejemplar', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, choices=[('m', 'Mantenimiento'), ('p', 'Bajo prestamo'), ('d', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Disponibilidad del libro', max_length=1)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.libro')),
            ],
            options={
                'verbose_name': 'Ejemplar de libro',
                'verbose_name_plural': 'Ejemplares de libros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateField(blank=True, help_text='Fecha en que el libro fue devuelto', null=True)),
                ('estado', models.CharField(blank=True, choices=[('a', 'Activo'), ('c', 'Completado'), ('r', 'Retrasado')], default='a', help_text='Estado del préstamo', max_length=1)),
                ('ejemplar', models.ForeignKey(help_text='Seleccione el ejemplar que se desea tomar a préstamo', on_delete=django.db.models.deletion.CASCADE, to='catalogo.ejemplarlibro')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
