# Generated by Django 5.1.4 on 2025-03-28 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ManyToManyField(help_text='Escoja un género para este libro', to='catalogo.genero'),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(help_text='Seleccione el autor del libro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor'),
        ),
    ]
