# Generated by Django 5.1.4 on 2025-04-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio_id_remoto', models.PositiveIntegerField()),
                ('titulo_espacio', models.CharField(max_length=200)),
                ('biblioteca_origen', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.perfilusuario')),
            ],
            options={
                'unique_together': {('espacio_id_remoto', 'biblioteca_origen', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
