# Generated by Django 5.1.4 on 2025-03-27 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('dni', models.CharField(blank=True, help_text='Ingrese su DNI', max_length=9, null=True, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=6, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Ingrese la dirección de su domicilio', max_length=250, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=40, null=True)),
                ('provincia', models.CharField(blank=True, max_length=40, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='')),
                ('bio', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'ordering': ['created'],
            },
        ),
    ]
