# Generated by Django 5.1.4 on 2025-02-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='ejemplarlibro',
            options={'ordering': ['id'], 'verbose_name': 'Ejemplar de libro', 'verbose_name_plural': 'Ejemplares de libros'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuarios'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha_prestamo'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
    ]
