# Generated by Django 5.1.4 on 2025-02-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_autor_options_alter_ejemplarlibro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
