# Generated by Django 5.1.4 on 2025-02-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_perfilusuario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ciudad',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_postal',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='provincia',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
