# Generated by Django 5.1.4 on 2025-02-14 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_perfilusuario_ciudad_perfilusuario_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefono',
        ),
    ]
