# Generated by Django 5.1.4 on 2025-02-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_perfilusuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.svg', null=True, upload_to='avatars/'),
        ),
    ]
