# Generated by Django 5.1.4 on 2025-03-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('catalogo', '0012_alter_perfilusuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(help_text='Seleccione el usuario asociado a este préstamo', on_delete=django.db.models.deletion.CASCADE, to='autenticacion.perfilusuario'),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
