# Generated by Django 5.1.4 on 2025-03-27 21:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('catalogo', '0013_alter_prestamo_usuario_delete_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='ejemplarlibro',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='ejemplar',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='usuario',
        ),
        migrations.CreateModel(
            name='PrestamoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_libro', models.CharField(max_length=200)),
                ('biblioteca_origen', models.CharField(max_length=100)),
                ('ejemplar_id', models.CharField(max_length=100)),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('a', 'Activo'), ('d', 'Devuelto'), ('r', 'Retrasado')], default='a', max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.perfilusuario')),
            ],
            options={
                'verbose_name': 'Préstamo de usuario',
                'verbose_name_plural': 'Préstamos de usuarios',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='EjemplarLibro',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
