# Generated by Django 5.1.4 on 2025-04-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_remove_libro_autor_remove_ejemplarlibro_libro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamousuario',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
