# Generated by Django 5.1.4 on 2025-04-07 13:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.PositiveIntegerField()),
                ('titulo_evento', models.CharField(max_length=200)),
                ('biblioteca_origen', models.CharField(max_length=100)),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.perfilusuario')),
            ],
            options={
                'verbose_name': 'Inscripción a evento',
                'verbose_name_plural': 'Inscripciones a eventos',
                'unique_together': {('usuario', 'evento_id', 'biblioteca_origen')},
            },
        ),
    ]
